#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3_1._0_
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LogIn")]
	public partial class QLNSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertACCOUNTT(ACCOUNTT instance);
    partial void UpdateACCOUNTT(ACCOUNTT instance);
    partial void DeleteACCOUNTT(ACCOUNTT instance);
    partial void Insertnhanvien(nhanvien instance);
    partial void Updatenhanvien(nhanvien instance);
    partial void Deletenhanvien(nhanvien instance);
    partial void Inserttheloai(theloai instance);
    partial void Updatetheloai(theloai instance);
    partial void Deletetheloai(theloai instance);
    partial void Insertnxb(nxb instance);
    partial void Updatenxb(nxb instance);
    partial void Deletenxb(nxb instance);
    partial void Inserttacgia(tacgia instance);
    partial void Updatetacgia(tacgia instance);
    partial void Deletetacgia(tacgia instance);
    partial void Insertdocgia(docgia instance);
    partial void Updatedocgia(docgia instance);
    partial void Deletedocgia(docgia instance);
    partial void Insertsach(sach instance);
    partial void Updatesach(sach instance);
    partial void Deletesach(sach instance);
    #endregion
		
		public QLNSDataContext() : 
				base(global::PBL3_1._0_.Properties.Settings.Default.LogInConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ACCOUNTT> ACCOUNTTs
		{
			get
			{
				return this.GetTable<ACCOUNTT>();
			}
		}
		
		public System.Data.Linq.Table<nhanvien> nhanviens
		{
			get
			{
				return this.GetTable<nhanvien>();
			}
		}
		
		public System.Data.Linq.Table<theloai> theloais
		{
			get
			{
				return this.GetTable<theloai>();
			}
		}
		
		public System.Data.Linq.Table<nxb> nxbs
		{
			get
			{
				return this.GetTable<nxb>();
			}
		}
		
		public System.Data.Linq.Table<tacgia> tacgias
		{
			get
			{
				return this.GetTable<tacgia>();
			}
		}
		
		public System.Data.Linq.Table<docgia> docgias
		{
			get
			{
				return this.GetTable<docgia>();
			}
		}
		
		public System.Data.Linq.Table<sach> saches
		{
			get
			{
				return this.GetTable<sach>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ACCOUNTT")]
	public partial class ACCOUNTT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Uers;
		
		private string _Taikhoan;
		
		private string _MatKhau;
		
		private string _Email;
		
		private System.Nullable<int> _ID_POSITION;
		
		private EntitySet<nhanvien> _nhanviens;
		
		private EntitySet<docgia> _docgias;
		
		private EntitySet<sach> _saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_UersChanging(int value);
    partial void OnID_UersChanged();
    partial void OnTaikhoanChanging(string value);
    partial void OnTaikhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnID_POSITIONChanging(System.Nullable<int> value);
    partial void OnID_POSITIONChanged();
    #endregion
		
		public ACCOUNTT()
		{
			this._nhanviens = new EntitySet<nhanvien>(new Action<nhanvien>(this.attach_nhanviens), new Action<nhanvien>(this.detach_nhanviens));
			this._docgias = new EntitySet<docgia>(new Action<docgia>(this.attach_docgias), new Action<docgia>(this.detach_docgias));
			this._saches = new EntitySet<sach>(new Action<sach>(this.attach_saches), new Action<sach>(this.detach_saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Uers", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Uers
		{
			get
			{
				return this._ID_Uers;
			}
			set
			{
				if ((this._ID_Uers != value))
				{
					this.OnID_UersChanging(value);
					this.SendPropertyChanging();
					this._ID_Uers = value;
					this.SendPropertyChanged("ID_Uers");
					this.OnID_UersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taikhoan", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Taikhoan
		{
			get
			{
				return this._Taikhoan;
			}
			set
			{
				if ((this._Taikhoan != value))
				{
					this.OnTaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Taikhoan = value;
					this.SendPropertyChanged("Taikhoan");
					this.OnTaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_POSITION", DbType="Int")]
		public System.Nullable<int> ID_POSITION
		{
			get
			{
				return this._ID_POSITION;
			}
			set
			{
				if ((this._ID_POSITION != value))
				{
					this.OnID_POSITIONChanging(value);
					this.SendPropertyChanging();
					this._ID_POSITION = value;
					this.SendPropertyChanged("ID_POSITION");
					this.OnID_POSITIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ACCOUNTT_nhanvien", Storage="_nhanviens", ThisKey="ID_Uers", OtherKey="ID_Uers")]
		public EntitySet<nhanvien> nhanviens
		{
			get
			{
				return this._nhanviens;
			}
			set
			{
				this._nhanviens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ACCOUNTT_docgia", Storage="_docgias", ThisKey="ID_Uers", OtherKey="ID_Uers")]
		public EntitySet<docgia> docgias
		{
			get
			{
				return this._docgias;
			}
			set
			{
				this._docgias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ACCOUNTT_sach", Storage="_saches", ThisKey="ID_Uers", OtherKey="ID_Uers")]
		public EntitySet<sach> saches
		{
			get
			{
				return this._saches;
			}
			set
			{
				this._saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_nhanviens(nhanvien entity)
		{
			this.SendPropertyChanging();
			entity.ACCOUNTT = this;
		}
		
		private void detach_nhanviens(nhanvien entity)
		{
			this.SendPropertyChanging();
			entity.ACCOUNTT = null;
		}
		
		private void attach_docgias(docgia entity)
		{
			this.SendPropertyChanging();
			entity.ACCOUNTT = this;
		}
		
		private void detach_docgias(docgia entity)
		{
			this.SendPropertyChanging();
			entity.ACCOUNTT = null;
		}
		
		private void attach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.ACCOUNTT = this;
		}
		
		private void detach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.ACCOUNTT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhanvien")]
	public partial class nhanvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _manhanvien;
		
		private string _tennhanvien;
		
		private System.Nullable<bool> _gioitinh;
		
		private string _sdt;
		
		private string _diachi;
		
		private System.Nullable<int> _ID_Uers;
		
		private EntityRef<ACCOUNTT> _ACCOUNTT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanhanvienChanging(string value);
    partial void OnmanhanvienChanged();
    partial void OntennhanvienChanging(string value);
    partial void OntennhanvienChanged();
    partial void OngioitinhChanging(System.Nullable<bool> value);
    partial void OngioitinhChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnID_UersChanging(System.Nullable<int> value);
    partial void OnID_UersChanged();
    #endregion
		
		public nhanvien()
		{
			this._ACCOUNTT = default(EntityRef<ACCOUNTT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manhanvien", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string manhanvien
		{
			get
			{
				return this._manhanvien;
			}
			set
			{
				if ((this._manhanvien != value))
				{
					this.OnmanhanvienChanging(value);
					this.SendPropertyChanging();
					this._manhanvien = value;
					this.SendPropertyChanged("manhanvien");
					this.OnmanhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennhanvien", DbType="NChar(20)")]
		public string tennhanvien
		{
			get
			{
				return this._tennhanvien;
			}
			set
			{
				if ((this._tennhanvien != value))
				{
					this.OntennhanvienChanging(value);
					this.SendPropertyChanging();
					this._tennhanvien = value;
					this.SendPropertyChanged("tennhanvien");
					this.OntennhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="Bit")]
		public System.Nullable<bool> gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="NChar(20)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NChar(20)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Uers", DbType="Int")]
		public System.Nullable<int> ID_Uers
		{
			get
			{
				return this._ID_Uers;
			}
			set
			{
				if ((this._ID_Uers != value))
				{
					if (this._ACCOUNTT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_UersChanging(value);
					this.SendPropertyChanging();
					this._ID_Uers = value;
					this.SendPropertyChanged("ID_Uers");
					this.OnID_UersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ACCOUNTT_nhanvien", Storage="_ACCOUNTT", ThisKey="ID_Uers", OtherKey="ID_Uers", IsForeignKey=true)]
		public ACCOUNTT ACCOUNTT
		{
			get
			{
				return this._ACCOUNTT.Entity;
			}
			set
			{
				ACCOUNTT previousValue = this._ACCOUNTT.Entity;
				if (((previousValue != value) 
							|| (this._ACCOUNTT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ACCOUNTT.Entity = null;
						previousValue.nhanviens.Remove(this);
					}
					this._ACCOUNTT.Entity = value;
					if ((value != null))
					{
						value.nhanviens.Add(this);
						this._ID_Uers = value.ID_Uers;
					}
					else
					{
						this._ID_Uers = default(Nullable<int>);
					}
					this.SendPropertyChanged("ACCOUNTT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.theloai")]
	public partial class theloai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _matheloai;
		
		private string _tentheloai;
		
		private EntitySet<sach> _saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatheloaiChanging(string value);
    partial void OnmatheloaiChanged();
    partial void OntentheloaiChanging(string value);
    partial void OntentheloaiChanged();
    #endregion
		
		public theloai()
		{
			this._saches = new EntitySet<sach>(new Action<sach>(this.attach_saches), new Action<sach>(this.detach_saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matheloai", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string matheloai
		{
			get
			{
				return this._matheloai;
			}
			set
			{
				if ((this._matheloai != value))
				{
					this.OnmatheloaiChanging(value);
					this.SendPropertyChanging();
					this._matheloai = value;
					this.SendPropertyChanged("matheloai");
					this.OnmatheloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tentheloai", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string tentheloai
		{
			get
			{
				return this._tentheloai;
			}
			set
			{
				if ((this._tentheloai != value))
				{
					this.OntentheloaiChanging(value);
					this.SendPropertyChanging();
					this._tentheloai = value;
					this.SendPropertyChanged("tentheloai");
					this.OntentheloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="theloai_sach", Storage="_saches", ThisKey="matheloai", OtherKey="matheloai")]
		public EntitySet<sach> saches
		{
			get
			{
				return this._saches;
			}
			set
			{
				this._saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.theloai = this;
		}
		
		private void detach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.theloai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nxb")]
	public partial class nxb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _manxb;
		
		private string _tennxb;
		
		private string _diachi;
		
		private EntitySet<sach> _saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanxbChanging(string value);
    partial void OnmanxbChanged();
    partial void OntennxbChanging(string value);
    partial void OntennxbChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    #endregion
		
		public nxb()
		{
			this._saches = new EntitySet<sach>(new Action<sach>(this.attach_saches), new Action<sach>(this.detach_saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manxb", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string manxb
		{
			get
			{
				return this._manxb;
			}
			set
			{
				if ((this._manxb != value))
				{
					this.OnmanxbChanging(value);
					this.SendPropertyChanging();
					this._manxb = value;
					this.SendPropertyChanged("manxb");
					this.OnmanxbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennxb", DbType="NChar(10)")]
		public string tennxb
		{
			get
			{
				return this._tennxb;
			}
			set
			{
				if ((this._tennxb != value))
				{
					this.OntennxbChanging(value);
					this.SendPropertyChanging();
					this._tennxb = value;
					this.SendPropertyChanged("tennxb");
					this.OntennxbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NChar(10)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nxb_sach", Storage="_saches", ThisKey="manxb", OtherKey="manxb")]
		public EntitySet<sach> saches
		{
			get
			{
				return this._saches;
			}
			set
			{
				this._saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.nxb = this;
		}
		
		private void detach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.nxb = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tacgia")]
	public partial class tacgia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _matacgia;
		
		private string _tentacgia;
		
		private EntitySet<sach> _saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatacgiaChanging(string value);
    partial void OnmatacgiaChanged();
    partial void OntentacgiaChanging(string value);
    partial void OntentacgiaChanged();
    #endregion
		
		public tacgia()
		{
			this._saches = new EntitySet<sach>(new Action<sach>(this.attach_saches), new Action<sach>(this.detach_saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matacgia", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string matacgia
		{
			get
			{
				return this._matacgia;
			}
			set
			{
				if ((this._matacgia != value))
				{
					this.OnmatacgiaChanging(value);
					this.SendPropertyChanging();
					this._matacgia = value;
					this.SendPropertyChanged("matacgia");
					this.OnmatacgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tentacgia", DbType="NChar(10)")]
		public string tentacgia
		{
			get
			{
				return this._tentacgia;
			}
			set
			{
				if ((this._tentacgia != value))
				{
					this.OntentacgiaChanging(value);
					this.SendPropertyChanging();
					this._tentacgia = value;
					this.SendPropertyChanged("tentacgia");
					this.OntentacgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tacgia_sach", Storage="_saches", ThisKey="matacgia", OtherKey="matacgia")]
		public EntitySet<sach> saches
		{
			get
			{
				return this._saches;
			}
			set
			{
				this._saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.tacgia = this;
		}
		
		private void detach_saches(sach entity)
		{
			this.SendPropertyChanging();
			entity.tacgia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.docgia")]
	public partial class docgia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _madocgia;
		
		private string _hoten;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private System.Nullable<bool> _gioitinh;
		
		private string _diachi;
		
		private string _sdt;
		
		private System.Nullable<int> _ID_Uers;
		
		private EntityRef<ACCOUNTT> _ACCOUNTT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmadocgiaChanging(string value);
    partial void OnmadocgiaChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OngioitinhChanging(System.Nullable<bool> value);
    partial void OngioitinhChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OnID_UersChanging(System.Nullable<int> value);
    partial void OnID_UersChanged();
    #endregion
		
		public docgia()
		{
			this._ACCOUNTT = default(EntityRef<ACCOUNTT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madocgia", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string madocgia
		{
			get
			{
				return this._madocgia;
			}
			set
			{
				if ((this._madocgia != value))
				{
					this.OnmadocgiaChanging(value);
					this.SendPropertyChanging();
					this._madocgia = value;
					this.SendPropertyChanged("madocgia");
					this.OnmadocgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NChar(20)")]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="Bit")]
		public System.Nullable<bool> gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NChar(20)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="NChar(20)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Uers", DbType="Int")]
		public System.Nullable<int> ID_Uers
		{
			get
			{
				return this._ID_Uers;
			}
			set
			{
				if ((this._ID_Uers != value))
				{
					if (this._ACCOUNTT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_UersChanging(value);
					this.SendPropertyChanging();
					this._ID_Uers = value;
					this.SendPropertyChanged("ID_Uers");
					this.OnID_UersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ACCOUNTT_docgia", Storage="_ACCOUNTT", ThisKey="ID_Uers", OtherKey="ID_Uers", IsForeignKey=true)]
		public ACCOUNTT ACCOUNTT
		{
			get
			{
				return this._ACCOUNTT.Entity;
			}
			set
			{
				ACCOUNTT previousValue = this._ACCOUNTT.Entity;
				if (((previousValue != value) 
							|| (this._ACCOUNTT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ACCOUNTT.Entity = null;
						previousValue.docgias.Remove(this);
					}
					this._ACCOUNTT.Entity = value;
					if ((value != null))
					{
						value.docgias.Add(this);
						this._ID_Uers = value.ID_Uers;
					}
					else
					{
						this._ID_Uers = default(Nullable<int>);
					}
					this.SendPropertyChanged("ACCOUNTT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sach")]
	public partial class sach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _masach;
		
		private string _tensach;
		
		private System.Nullable<int> _namxb;
		
		private string _manxb;
		
		private string _matheloai;
		
		private string _matacgia;
		
		private System.Nullable<int> _soluong;
		
		private string _ghichu;
		
		private string _khusach;
		
		private System.Nullable<int> _giatien;
		
		private System.Nullable<int> _ID_Uers;
		
		private System.Data.Linq.Binary _picture;
		
		private EntityRef<ACCOUNTT> _ACCOUNTT;
		
		private EntityRef<nxb> _nxb;
		
		private EntityRef<tacgia> _tacgia;
		
		private EntityRef<theloai> _theloai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmasachChanging(string value);
    partial void OnmasachChanged();
    partial void OntensachChanging(string value);
    partial void OntensachChanged();
    partial void OnnamxbChanging(System.Nullable<int> value);
    partial void OnnamxbChanged();
    partial void OnmanxbChanging(string value);
    partial void OnmanxbChanged();
    partial void OnmatheloaiChanging(string value);
    partial void OnmatheloaiChanged();
    partial void OnmatacgiaChanging(string value);
    partial void OnmatacgiaChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    partial void OnghichuChanging(string value);
    partial void OnghichuChanged();
    partial void OnkhusachChanging(string value);
    partial void OnkhusachChanged();
    partial void OngiatienChanging(System.Nullable<int> value);
    partial void OngiatienChanged();
    partial void OnID_UersChanging(System.Nullable<int> value);
    partial void OnID_UersChanged();
    partial void OnpictureChanging(System.Data.Linq.Binary value);
    partial void OnpictureChanged();
    #endregion
		
		public sach()
		{
			this._ACCOUNTT = default(EntityRef<ACCOUNTT>);
			this._nxb = default(EntityRef<nxb>);
			this._tacgia = default(EntityRef<tacgia>);
			this._theloai = default(EntityRef<theloai>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masach", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string masach
		{
			get
			{
				return this._masach;
			}
			set
			{
				if ((this._masach != value))
				{
					this.OnmasachChanging(value);
					this.SendPropertyChanging();
					this._masach = value;
					this.SendPropertyChanged("masach");
					this.OnmasachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tensach", DbType="NChar(20)")]
		public string tensach
		{
			get
			{
				return this._tensach;
			}
			set
			{
				if ((this._tensach != value))
				{
					this.OntensachChanging(value);
					this.SendPropertyChanging();
					this._tensach = value;
					this.SendPropertyChanged("tensach");
					this.OntensachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_namxb", DbType="Int")]
		public System.Nullable<int> namxb
		{
			get
			{
				return this._namxb;
			}
			set
			{
				if ((this._namxb != value))
				{
					this.OnnamxbChanging(value);
					this.SendPropertyChanging();
					this._namxb = value;
					this.SendPropertyChanged("namxb");
					this.OnnamxbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manxb", DbType="NChar(10)")]
		public string manxb
		{
			get
			{
				return this._manxb;
			}
			set
			{
				if ((this._manxb != value))
				{
					if (this._nxb.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanxbChanging(value);
					this.SendPropertyChanging();
					this._manxb = value;
					this.SendPropertyChanged("manxb");
					this.OnmanxbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matheloai", DbType="NChar(10)")]
		public string matheloai
		{
			get
			{
				return this._matheloai;
			}
			set
			{
				if ((this._matheloai != value))
				{
					if (this._theloai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmatheloaiChanging(value);
					this.SendPropertyChanging();
					this._matheloai = value;
					this.SendPropertyChanged("matheloai");
					this.OnmatheloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matacgia", DbType="NChar(10)")]
		public string matacgia
		{
			get
			{
				return this._matacgia;
			}
			set
			{
				if ((this._matacgia != value))
				{
					if (this._tacgia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmatacgiaChanging(value);
					this.SendPropertyChanging();
					this._matacgia = value;
					this.SendPropertyChanged("matacgia");
					this.OnmatacgiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghichu", DbType="NChar(20)")]
		public string ghichu
		{
			get
			{
				return this._ghichu;
			}
			set
			{
				if ((this._ghichu != value))
				{
					this.OnghichuChanging(value);
					this.SendPropertyChanging();
					this._ghichu = value;
					this.SendPropertyChanged("ghichu");
					this.OnghichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khusach", DbType="NChar(10)")]
		public string khusach
		{
			get
			{
				return this._khusach;
			}
			set
			{
				if ((this._khusach != value))
				{
					this.OnkhusachChanging(value);
					this.SendPropertyChanging();
					this._khusach = value;
					this.SendPropertyChanged("khusach");
					this.OnkhusachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giatien", DbType="Int")]
		public System.Nullable<int> giatien
		{
			get
			{
				return this._giatien;
			}
			set
			{
				if ((this._giatien != value))
				{
					this.OngiatienChanging(value);
					this.SendPropertyChanging();
					this._giatien = value;
					this.SendPropertyChanged("giatien");
					this.OngiatienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Uers", DbType="Int")]
		public System.Nullable<int> ID_Uers
		{
			get
			{
				return this._ID_Uers;
			}
			set
			{
				if ((this._ID_Uers != value))
				{
					if (this._ACCOUNTT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_UersChanging(value);
					this.SendPropertyChanging();
					this._ID_Uers = value;
					this.SendPropertyChanged("ID_Uers");
					this.OnID_UersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_picture", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary picture
		{
			get
			{
				return this._picture;
			}
			set
			{
				if ((this._picture != value))
				{
					this.OnpictureChanging(value);
					this.SendPropertyChanging();
					this._picture = value;
					this.SendPropertyChanged("picture");
					this.OnpictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ACCOUNTT_sach", Storage="_ACCOUNTT", ThisKey="ID_Uers", OtherKey="ID_Uers", IsForeignKey=true)]
		public ACCOUNTT ACCOUNTT
		{
			get
			{
				return this._ACCOUNTT.Entity;
			}
			set
			{
				ACCOUNTT previousValue = this._ACCOUNTT.Entity;
				if (((previousValue != value) 
							|| (this._ACCOUNTT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ACCOUNTT.Entity = null;
						previousValue.saches.Remove(this);
					}
					this._ACCOUNTT.Entity = value;
					if ((value != null))
					{
						value.saches.Add(this);
						this._ID_Uers = value.ID_Uers;
					}
					else
					{
						this._ID_Uers = default(Nullable<int>);
					}
					this.SendPropertyChanged("ACCOUNTT");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nxb_sach", Storage="_nxb", ThisKey="manxb", OtherKey="manxb", IsForeignKey=true)]
		public nxb nxb
		{
			get
			{
				return this._nxb.Entity;
			}
			set
			{
				nxb previousValue = this._nxb.Entity;
				if (((previousValue != value) 
							|| (this._nxb.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nxb.Entity = null;
						previousValue.saches.Remove(this);
					}
					this._nxb.Entity = value;
					if ((value != null))
					{
						value.saches.Add(this);
						this._manxb = value.manxb;
					}
					else
					{
						this._manxb = default(string);
					}
					this.SendPropertyChanged("nxb");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tacgia_sach", Storage="_tacgia", ThisKey="matacgia", OtherKey="matacgia", IsForeignKey=true)]
		public tacgia tacgia
		{
			get
			{
				return this._tacgia.Entity;
			}
			set
			{
				tacgia previousValue = this._tacgia.Entity;
				if (((previousValue != value) 
							|| (this._tacgia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tacgia.Entity = null;
						previousValue.saches.Remove(this);
					}
					this._tacgia.Entity = value;
					if ((value != null))
					{
						value.saches.Add(this);
						this._matacgia = value.matacgia;
					}
					else
					{
						this._matacgia = default(string);
					}
					this.SendPropertyChanged("tacgia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="theloai_sach", Storage="_theloai", ThisKey="matheloai", OtherKey="matheloai", IsForeignKey=true)]
		public theloai theloai
		{
			get
			{
				return this._theloai.Entity;
			}
			set
			{
				theloai previousValue = this._theloai.Entity;
				if (((previousValue != value) 
							|| (this._theloai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._theloai.Entity = null;
						previousValue.saches.Remove(this);
					}
					this._theloai.Entity = value;
					if ((value != null))
					{
						value.saches.Add(this);
						this._matheloai = value.matheloai;
					}
					else
					{
						this._matheloai = default(string);
					}
					this.SendPropertyChanged("theloai");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
